services:
  calculator:
    build: .
    container_name: calculator
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.calculator.rule=Host(`calculator.ecotron.co.in`)"
      - "traefik.http.routers.calculator.entrypoints=websecure"
      - "traefik.http.routers.calculator.tls.certresolver=myresolver"
      - "traefik.http.services.calculator.loadbalancer.server.port=8080"

networks:
  traefik:
    external: true
