services:
  ecocalculator:
    build: .
    container_name: ecocalculator
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.ecocalculator.rule=Host(`ecocalculator.ecotron.co.in`)"
      - "traefik.http.routers.ecocalculator.entrypoints=websecure"
      - "traefik.http.routers.ecocalculator.tls.certresolver=myresolver"
      - "traefik.http.services.ecocalculator.loadbalancer.server.port=8080"

networks:
  traefik:
    external: true
