name: Deploy Calculator

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            if [ -d "/root/calculator" ] && [ ! -d "/root/ecocalculator" ]; then
              mv /root/calculator /root/ecocalculator
            fi
            if [ ! -d "/root/ecocalculator" ]; then
              git clone https://github.com/omkar861856/insect.git /root/ecocalculator
            fi
            cd /root/ecocalculator
            git pull
            docker compose up -d --build --remove-orphans
